version: '3.2'
services:
 hue2mqttpy:
    build: .
    container_name: hue2mqttpy
    restart: unless-stopped
    volumes:
      - "/home/pi/hue2mqtt/hue2mqtt.toml:/hue2mqtt-python/hue2mqtt.toml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
